import { engineeringDomainsSchema } from "@/features/engineering/schemas/engineering-domain-schema";

const engineeringDomainsData = [
  {
    id: "frontend",
    index: "01",
    code: "FE",
    name: "Frontend",
    statement:
      "Engineering responsive, accessible and high-performance interfaces as structured application systems.",
    capabilities: [
      "Component architecture",
      "State and data orchestration",
      "Responsive design",
      "Accessibility",
      "Interaction and motion",
      "Performance optimization",
      "Rendering and SEO",
      "Reusable component systems",
      "Server state management",
      "Real-time data interfaces",
    ],
    technologies: [
      "React",
      "Next.js",
      "TypeScript",
      "JavaScript ES6+",
      "HTML5",
      "CSS3",
      "Tailwind CSS",
      "React Router",
      "TanStack Query",
      "Zustand",
      "React Hook Form",
      "Zod",
      "shadcn/ui",
      "Motion / Framer Motion",
      "Sanity CMS",
      "Vite",
      "Lighthouse",
    ],
  },
  {
    id: "backend",
    index: "02",
    code: "BE",
    name: "Backend",
    statement:
      "Designing application services, APIs and server-side systems with explicit contracts, reliable validation and maintainable separation of responsibilities, while expanding into Java and Spring Boot.",
    capabilities: [
      "REST API design",
      "API integration",
      "Authentication flows",
      "Authorization",
      "Validation",
      "Error handling",
      "Service architecture",
      "Data access",
      "Legacy code adaptation",
      "Separation of responsibilities",
    ],
    technologies: [
      "Node.js",
      "Express",
      "NestJS",
      "TypeScript",
      "JavaScript ES6+",
      "JWT",
      "Postman",
      "PostgreSQL",
      "MongoDB",
      "Mongoose",
      "Prisma ORM",
      "Drizzle",
      "Zod",
      "Java",
      "Spring Boot",
    ],
  },
  {
    id: "data",
    index: "03",
    code: "DA",
    name: "Data",
    statement:
      "Modeling, querying and connecting persistent and content-driven data to application behavior through predictable data flows.",
    capabilities: [
      "Data modeling",
      "Relational design",
      "Document modeling",
      "Query design",
      "Schema validation",
      "Client-server synchronization",
      "Content modeling",
      "Persistent data integration",
    ],
    technologies: [
      "PostgreSQL",
      "MongoDB",
      "Mongoose",
      "Prisma ORM",
      "Drizzle",
      "SQL",
      "Zod",
      "Sanity CMS",
      "TanStack Query",
    ],
  },
  {
    id: "quality",
    index: "04",
    code: "QA",
    name: "Quality",
    statement:
      "Protecting system behavior through automated verification, static analysis, technical auditing and reproducible quality gates.",
    capabilities: [
      "Unit testing",
      "Component testing",
      "Integration testing",
      "Static analysis",
      "Type safety",
      "Quality gates",
      "Performance auditing",
      "Accessibility auditing",
      "Code review",
      "Schema validation",
    ],
    technologies: [
      "Vitest",
      "Jest",
      "React Testing Library",
      "Playwright",
      "ESLint",
      "Prettier",
      "TypeScript",
      "Zod",
      "Postman",
      "Lighthouse",
      "SonarQube",
      "GitHub Actions",
    ],
  },
  {
    id: "delivery",
    index: "05",
    code: "DL",
    name: "Delivery",
    statement:
      "Moving software from repository to production through controlled collaboration, automation and repeatable delivery workflows.",
    capabilities: [
      "Continuous integration",
      "Continuous delivery",
      "Build validation",
      "Deployment workflows",
      "Environment configuration",
      "Release discipline",
      "Feature branch workflow",
      "Pull request workflows",
      "Code review",
      "Scrum and Agile delivery",
    ],
    technologies: ["GitHub Actions", "Jenkins", "Docker", "Vercel", "AWS", "Git", "GitHub"],
  },
  {
    id: "tooling",
    index: "06",
    code: "TL",
    name: "Tooling",
    statement:
      "Building disciplined development environments through automation, conventions and reliable engineering workflows.",
    capabilities: [
      "Git workflows",
      "Repository architecture",
      "Pre-commit automation",
      "Code formatting",
      "Dependency management",
      "Developer experience",
      "Automation scripting",
      "Debugging and refactoring",
      "AI-assisted development workflows",
      "Technical documentation",
    ],
    technologies: [
      "Git",
      "GitHub",
      "npm",
      "Husky",
      "lint-staged",
      "Prettier",
      "Vite",
      "Turbopack",
      "Python",
    ],
  },
] as const;

export const engineeringDomains = engineeringDomainsSchema.parse(engineeringDomainsData);
